"""Add available_beds to availability

Revision ID: 28109b2179bc
Revises: 45380b4f16f3
Create Date: 2026-02-07 19:22:41.128526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28109b2179bc'
down_revision = '45380b4f16f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambulances',
    sa.Column('ambulance_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ON_CALL', 'MAINTENANCE', name='ambulance_status'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ambulance_id'),
    sa.UniqueConstraint('vehicle_number')
    )
    with op.batch_alter_table('ambulance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('vehicle_number'))

    op.drop_table('ambulance')
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_beds', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('is_emergency_ready')
        batch_op.drop_column('last_updated')
        batch_op.drop_column('icu_beds')
        batch_op.drop_column('emergency_beds')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_beds', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('icu_beds', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_updated', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('is_emergency_ready', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('available_beds')

    op.create_table('ambulance',
    sa.Column('ambulance_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehicle_number', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('latitude', mysql.FLOAT(), nullable=False),
    sa.Column('longitude', mysql.FLOAT(), nullable=False),
    sa.Column('status', mysql.ENUM('AVAILABLE', 'ON_CALL', 'MAINTENANCE'), nullable=True),
    sa.Column('last_updated', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('ambulance_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ambulance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('vehicle_number'), ['vehicle_number'], unique=True)

    op.drop_table('ambulances')
    # ### end Alembic commands ###
