"""add_location_history_table

Revision ID: 2e70d55bf055
Revises: ae11759ba16c
Create Date: 2026-03-23 19:35:01.759001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e70d55bf055'
down_revision = 'ae11759ba16c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ambulance_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('is_offline_record', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ambulance_id'], ['ambulances.ambulance_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_history_ambulance_id'), ['ambulance_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_history_ambulance_id'))

    op.drop_table('location_history')
    # ### end Alembic commands ###
