"""Added hospital, ambulance, availability models

Revision ID: 45380b4f16f3
Revises: 
Create Date: 2026-01-30 22:50:24.746420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45380b4f16f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambulances',
    sa.Column('ambulance_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ON_CALL', 'MAINTENANCE', name='ambulance_status'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ambulance_id'),
    sa.UniqueConstraint('vehicle_number')
    )
    op.create_table('hospitals',
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('hospital_id')
    )
    op.create_table('availability',
    sa.Column('availability_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('emergency_beds', sa.Integer(), nullable=False),
    sa.Column('icu_beds', sa.Integer(), nullable=False),
    sa.Column('is_emergency_ready', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.hospital_id'], ),
    sa.PrimaryKeyConstraint('availability_id'),
    sa.UniqueConstraint('hospital_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('availability')
    op.drop_table('hospitals')
    op.drop_table('ambulances')
    # ### end Alembic commands ###
