"""add_gps_transfer_dual_sla_fields

Revision ID: 58c6d95acac9
Revises: 2e70d55bf055
Create Date: 2026-03-24 16:58:22.391945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c6d95acac9'
down_revision = '2e70d55bf055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accident_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('accident_longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('needs_transfer', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('required_speciality', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('transfer_legs', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dispatch_sla_deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('transport_sla_deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('scene_arrived_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('dispatch_response_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('transport_response_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_requests', schema=None) as batch_op:
        batch_op.drop_column('transport_response_time')
        batch_op.drop_column('dispatch_response_time')
        batch_op.drop_column('scene_arrived_at')
        batch_op.drop_column('transport_sla_deadline')
        batch_op.drop_column('dispatch_sla_deadline')
        batch_op.drop_column('transfer_legs')
        batch_op.drop_column('required_speciality')
        batch_op.drop_column('needs_transfer')
        batch_op.drop_column('accident_longitude')
        batch_op.drop_column('accident_latitude')

    # ### end Alembic commands ###
