"""Expand status enum

Revision ID: 7cd3d13de86a
Revises: 58c6d95acac9
Create Date: 2026-03-25 11:33:44.522253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7cd3d13de86a'
down_revision = '58c6d95acac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pending', 'allocated', 'en_route', 'arrived', 'first_aid', 'transfer_en_route', 'in_progress', 'completed', 'cancelled', 'escalated'),
               nullable=True,
               existing_server_default=sa.text("'pending'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pending', 'allocated', 'en_route', 'arrived', 'first_aid', 'transfer_en_route', 'in_progress', 'completed', 'cancelled', 'escalated'),
               nullable=False,
               existing_server_default=sa.text("'pending'"))

    # ### end Alembic commands ###
