"""Refine emergency and relationships

Revision ID: 9f3731507294
Revises: 28109b2179bc
Create Date: 2026-02-16 18:09:39.109573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f3731507294'
down_revision = '28109b2179bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_requests', schema=None) as batch_op:
        batch_op.alter_column('emergency_type',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('pending', 'allocated', 'in_progress', 'completed', 'cancelled', name='emergency_status'),
               existing_nullable=True)
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'allocated', 'in_progress', 'completed', 'cancelled', name='emergency_status'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('emergency_type',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
