"""Updated relationships

Revision ID: a70d9a49927d
Revises: 9f3731507294
Create Date: 2026-02-16 19:09:04.639280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a70d9a49927d'
down_revision = '9f3731507294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.alter_column('hospital_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.alter_column('hospital_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
