"""Added severity and SLA to emergency

Revision ID: e0ada61d5e3e
Revises: a70d9a49927d
Create Date: 2026-02-19 19:05:52.675649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0ada61d5e3e'
down_revision = 'a70d9a49927d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ambulances', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('AVAILABLE', 'BUSY', 'MAINTENANCE', 'ON_CALL'),
               nullable=True)

    with op.batch_alter_table('emergency_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', name='emergency_severity'), nullable=False))
        batch_op.add_column(sa.Column('sla_deadline', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_emergency_requests_ambulance_id'), ['ambulance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_requests_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_requests_sla_deadline'), ['sla_deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_requests_status'))
        batch_op.drop_index(batch_op.f('ix_emergency_requests_sla_deadline'))
        batch_op.drop_index(batch_op.f('ix_emergency_requests_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_emergency_requests_created_at'))
        batch_op.drop_index(batch_op.f('ix_emergency_requests_ambulance_id'))
        batch_op.drop_column('sla_deadline')
        batch_op.drop_column('severity')

    with op.batch_alter_table('ambulances', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('AVAILABLE', 'BUSY', 'MAINTENANCE', 'ON_CALL'),
               nullable=False)

    # ### end Alembic commands ###
